UploadTest0
AlexandreTO/Projet pull request #65
Opened 2021-09-16 21:16 UTC by Aicha-j

affiche les images de produits et catégories.

2021-09-16 21:27 UTC, Loganghilardi commented on assets/js/components/front/Categories.js
> +        console.log(categories);
A supprimer

2021-09-16 21:28 UTC, Loganghilardi commented on assets/js/components/front/Products.js
> +        console.log(products);
idem

2021-09-16 21:29 UTC, AlexandreTO requested changes
T'as oublié de mettre à jour l'image du produit quand on clique dessus dans le fichier
`ProductView.js`

2021-09-16 21:31 UTC, Loganghilardi requested changes
Manque les updates, et l'affichage de l'image dans la page du produit sinon c nice

2021-09-17 07:02 UTC, Loganghilardi commented on assets/js/components/back/Products.js
> +                                        <img src={`/images/products/${product.image}`} alt="card-img-top"/>
<img src={`/images/products/${product.image}`} className="mw-100" alt="card-img-top"/>

2021-09-17 07:05 UTC, Loganghilardi commented on assets/js/components/back/ProductsView.js
> +                            <img src={`/images/products/${product.image}`} alt="card-img-top"/>
className="mw-100"

2021-09-17 07:05 UTC, Loganghilardi commented on assets/js/components/front/Categories.js
> +                                    <img src={`/images/products/${categorie.nameImage}`} alt="card-img-top"/>
className="mw-100"

2021-09-17 07:05 UTC, Loganghilardi commented on assets/js/components/front/Products.js
> +                                        <img src={`/images/products/${product.image}`} alt="card-img-top"/>
className="mw-100"

2021-09-17 07:05 UTC, Loganghilardi commented on assets/js/components/front/ProductsView.js
> +                            <img src={`/images/products/${product.image}`} alt="card-img-top"/>
className="mw-100"

2021-09-17 07:08 UTC, Loganghilardi commented on src/Controller/BackControllers/BackProductsController.php
> +            $entityManager->persist($product);
inutile

2021-09-17 07:09 UTC, Loganghilardi requested changes
Change les className des images vite fait et repush

2021-09-17 07:13 UTC, Loganghilardi approved these changes

2021-09-17 07:14 UTC, hakan9719 approved these changes

2021-09-17 07:14 UTC, AlexandreTO approved these changes

2021-09-17 07:15 UTC, merged